[package]
name = "ryzenmon-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.23.0"
influxdb2 = "0.5.2"
futures = "0.3.31"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8.19"
serde = { version = "1.0.214", features = ["derive"] }
once_cell = "1.10"